#!/bin/bash
#thank you, sirupsen
WINTITLE="Terminal - " # Name of the window (or part of it)
PROGRAMNAME="gnome-terminal" # Name of the program, so it can be opened if there's no window currently

# Lists all windows, if there's one containing $WINTITLE it'll return 1, and bring the current instance of the program to the front.
if [ `wmctrl -l | grep -c "$WINTITLE"` != 0 ]; then
	wmctrl -a "$WINTITLE"
# Else, it'll launch a new instance
else
  $PROGRAMNAME &
fi

# We're good!
exit 0